<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "owl_slider"
 *
 * Auto generated by Extension Builder 2014-02-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'owlSlider',
	'description' => 'Touch enabled jQuery plugin that lets you create beautiful responsive carousel slider.',
	'category' => 'misc',
	'author' => 'comsolit AG',
	'author_email' => 'info@comsolit.com',
	'author_company' => 'comsolit AG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0.99-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>